storage: /verdaccio/storage/data
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  'scuri':
    access: $all
    publish: $all 
  '@**':
    access: $all
    publish: $all 
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs
logs:
 - {type: stdout, format: pretty, level: trace}