version: "3.9"
services:
  verdaccio:
    image: verdaccio/verdaccio:5.23
    ports:
      - "4873:4873"
    volumes:
      - $PWD/.verdaccio/verdaccio/conf:/verdaccio/conf:rw
    container_name: verdaccio
